// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Bookmanagement.Entities
{
    public partial class BookAuthors
    {
        [Key]
        [Column("Author_Id")]
        public int AuthorId { get; set; }
        [Required]
        [Column("Author_Name")]
        [StringLength(50)]
        public string AuthorName { get; set; }
    }
}