// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Bookmanagement.Entities
{
    public partial class Filesmanagement
    {
        [Key]
        public int FilesId { get; set; }
        [Required]
        [StringLength(40)]
        public string Filesname { get; set; }
        [Required]
        public byte[] Files { get; set; }
        [Column("Is_deleted")]
        public bool IsDeleted { get; set; }
        [Column("Created_Time_stamp", TypeName = "datetime")]
        public DateTime CreatedTimeStamp { get; set; }
        [Column("Updated_Time_stamp", TypeName = "datetime")]
        public DateTime UpdatedTimeStamp { get; set; }
    }
}